base: /
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=14'
languages:
  -
    title: English
    enabled: true
    locale: en_US.UTF-8
    hreflang: en-US
    base: /
    websiteTitle: ''
    navigationTitle: English
    flag: us
    languageId: 0
rootPageId: 2
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\n#Allow: /typo3/sysext/frontend/Resources/Public/*\r\n\r\n\r\nSitemap: https:/write-down-url/sitemap.xml"
websiteTitle: ''
